holder_name = 'HolderName'

holder_tp = [
    [{'text': 'I am Mister ',
      'entity_type': None,
      'alias': None,
      'user_defined': False},
     {'text': 'Doe',
      'entity_type': '@sys.last-name',
      'alias': 'last-name',
      'user_defined': True}],
    [{'text': 'my name is ',
      'entity_type': None,
      'alias': None,
      'user_defined': False},
     {'text': 'Lucy',
      'entity_type': '@sys.given-name',
      'alias': 'given-name',
      'user_defined': True}],
    [{'text': 'I am ',
      'entity_type': None,
      'alias': None,
      'user_defined': False},
     {'text': 'Robert',
      'entity_type': '@sys.given-name',
      'alias': 'given-name',
      'user_defined': True}],
    [{'text': 'my name is ',
      'entity_type': None,
      'alias': None,
      'user_defined': False},
     {'text': 'John Doe',
      'entity_type': '@sys.person',
      'alias': 'person',
      'user_defined': True}],
    [{'text': 'sure, my name is ',
      'entity_type': None,
      'alias': None,
      'user_defined': False},
     {'text': 'Lucy Miller',
      'entity_type': '@sys.person',
      'alias': 'person',
      'user_defined': True}]
]

holder_mt = ['Alright, I got your name as $person. Where is your farm located?']

holder_params = [{'name': '',
                  'display_name': 'person',
                  'value': '$person',
                  'mandatory': True,
                  'entity_type_display_name': '@sys.person',
                  'prompts': ['Please, enter your full name.'],
                  'is_list': False},
                 {'name': '',
                  'display_name': 'last-name',
                  'value': 'last-name',
                  'mandatory': False,
                  'entity_type_display_name': '@sys.last-name',
                  'is_list': False},
                 {'name': '',
                  'display_name': 'given-name',
                  'value': 'given-name',
                  'mandatory': False,
                  'entity_type_display_name': '@sys.given-name',
                  'is_list': False}
                 ]
